maybe last fix

diff --git a/tutorials/data/user-mgr b/tutorials/data/user-mgr
--- a/tutorials/data/user-mgr
+++ b/tutorials/data/user-mgr
@@ -153,7 +153,7 @@ elif [[ "$cmd" == "unset" ]]; then
       esac
       echo "Unsetting override $k..."
       jq "del(.groups.\"$n\".overrides.\"$k\")" $s > $s.new && mv $s.new $s
-      [[ "$?" -eq 0 ]] || error 33 "something failed in area $s update. you may want to check your localcoda instance to see if all is still well..."
+      [[ "$?" -eq 0 ]] || error 33 "something failed in $s update. you may want to check your localcoda instance to see if all is still well..."
     done
     echo "Parameters unset successfully"
   fi
@@ -172,13 +172,16 @@ elif [[ "$cmd" == "ls" ]]; then
     fi  
   fi
 elif [[ "$cmd" == "del" ]]; then
-  #Check if area exists and is empty
-  [[ -z "$(ls -A "$a")"  ]] || error 32 "cannot remove non-empty area. First remove the contents of the $a folder."
-  rmdir "$a"
-  [[ "$?" -eq 0 ]] || error 65 "failed to remove $a directory. Maybe it does not exist or it is not empty."
-  jq ".items |= map(select(.path != \"$a\"))" $s > $s.new && mv $s $s.bak && mv $s.new $s
-  [[ "$?" -eq 0 ]] || error 33 "something failed in area $s update. you may want to check your localcoda instance to see if all is still well..."
-  echo "Area $a deleted successfully"
+  #Delete a user
+  if [[ "$a" == "user" ]]; then
+    jq "del(.users.\"$n\")" $s > $s.new && mv $s $s.bak && mv $s.new $s
+    [[ "$?" -eq 0 ]] || error 33 "something failed in $s update. you may want to check your localcoda instance to see if all is still well..."
+    echo "User $n deleted!"
+  else
+    jq "del(.groups.\"$n\")" $s > $s.new && mv $s $s.bak && mv $s.new $s
+    [[ "$?" -eq 0 ]] || error 33 "something failed in $s update. you may want to check your localcoda instance to see if all is still well..."
+    echo "Group $n deleted!"
+  fi
 elif [[ "$cmd" == "restore-backup" ]]; then
   #Check if backup exists
   [[ -f "$s.bak" ]] || error 36 "backup file does not exist"
